### ISSUE TITLE
xib转coding报错

### ISSUE THREAD

**Issue by EarthMass** [liubobo/automation#5]
操作“运行 Shell 脚本”遇到了错误：“Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/guohaixiang/Library/Services/project/automation/AInterface.py", line 56, in output_xib

map(xibparse.gen_xib_file,Util.readlines_from_stdin())
  File "/Users/xxx/Library/Services/project/automation/ATool/xibparse.py", line 199, in gen_xib_file
    uis = parse(root)
  File "/Users/xxx/Library/Services/project/automation/ATool/xibparse.py", line 77, in parse
    ui_list,ui_trees= find_uis(root)
  File "/Users/xxx/Library/Services/project/automation/ATool/xibparse.py", line 54, in find_uis
    ui = convent_dict2ui(child)
  File "/Users/xxx/Library/Services/project/automation/ATool/xibparse.py", line 40, in convent_dict2ui
    ui.name = ui.id + '_' + toCap(child.tag)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'”

**Comment by EarthMass** [comment]
是不是不支持 UICollectionViewCell

**Comment by liubobo** [comment]
目前不支持
